### ISSUE TITLE
Add Dan Bloch to the team page.

### ISSUE THREAD

**Issue by evedes** [iamfreeCodeCamp/iamfreecodecamp#14]
We're welcoming and onboarding @danbloch21 to our team and project.

We need to update the info on the team's page.
Me and @danbloch21 we'll do it soon-ish as a pair programming session to be scheduled. 🚀

**Comment by danbloch21** [comment]
Thanks Edo! Great to be involved and looking forward to collaborating with the team on this very worthwhile project.Very bestDanSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Eduardo Vedes ***@***.***> Date: 08/04/2021  19:40  (GMT+00:00) To: iamfreeCodeCamp/iamfreecodecamp ***@***.***> Cc: Dan Bloch ***@***.***>, Assign ***@***.***> Subject: [iamfreeCodeCamp/iamfreecodecamp] Add Dan Bloch to the team page. (#14) 

We're welcoming and onboarding @danbloch21 to our team and project.

We need to update the info on the team's page.

Me and @danbloch21 we'll do it soon-ish as a pair programming session to be scheduled. 🚀



—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamfreeCodeCamp/iamfreecodecamp/issues/14",

"url": "https://github.com/iamfreeCodeCamp/iamfreecodecamp/issues/14",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by evedes** [comment]
Good job @danbloch21 ❤️
